# 1. 定义测试环境
#    脚本会自动检测当前GPU，如果GPU名称包含在此列表的某个字符串中，测试将运行
#    例如, ["A100", "H100", "RTX 4090"]
target_gpus:
  "A800": "nvidia/nvidia-a100"

# 2. 定义模型层级的矩阵尺寸 (N, K)
#    M 的大小不在这里定义，而是由 batch size 和 sequence length 决定
#    在 prefill 阶段，sequence length 取一较大值，在 decode 阶段，sequence length 取 1
models:
  "Llama-3-8B-Layer":
    # N, K
    "FFN Up-proj": [14336, 4096]
    # "FFN Down-proj": [4096, 14336]
    "Attention": [4096, 4096]

# 3. 定义量化精度
#    格式为[W_dtype, A_dtype, out_dtype]
precisions:
  - ["float16", "float16", "float16"]  # Baseline
  - ["int4", "float16", "float16"]     # W4A16
  - ["int8", "int8", "float16"]        # W8A8

# 4. 定义 batch sizes 和 sequence_length
batch_sizes:
  - 1
  # - 2
  # - 4
  # - 8
  # - 16
  # - 32

sequence_length: 4096

# 5. 定义测试设置
test_settings:
  warmup_iterations: 20   # 预热运行次数
  test_iterations: 100    # 实际测量性能的运行次数